.TH man 1 "12 Jan 2021" "1.0" "find-time-range man page"
.SH NAME
find-time-range \- find files in a given time range and execute a command
.SH SYNOPSIS
find-time-range PATH PATTERN START RANGE COMMAND
.SH DESCRIPTION
No description yet
.SH EXAMPLE
find-time-range ~ '*.sh' 1610482903 3600 "wc -l"

Count the lines of every shell file under home directory
modified between (approx) Jan 12 21:20 and Jan 12 22:20
