FROM manjarolinux/base

ARG DOCKER_GID
ARG USER_ID
ARG USERNAME=dockerdev

RUN userdel builder
RUN groupadd -g $DOCKER_GID docker

RUN pacman -Sy --noconfirm \
    zsh \
    zsh-autosuggestions \
    zsh-completions \
    zsh-syntax-highlighting \
    zsh-theme-powerlevel10k \
    fzf \
    tmux \
    powerline \
    the_silver_searcher \
    python-pip \
    npm \
    go \
    jq \
    bat \
    ripgrep \
    fd \
    stow \
    docker \
    unzip

RUN useradd \
        --create-home \
        -u $USER_ID \
        -G docker \
        -s /usr/bin/zsh \
        $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER $USERNAME

RUN mkdir ~/tmp

RUN git clone https://aur.archlinux.org/lf.git ~/tmp/lf && \
    (cd ~/tmp/lf && makepkg) && \
    sudo pacman -U --noconfirm ~/tmp/lf/*.zst && \
    rm -rf ~/tmp/lf

RUN git clone https://github.com/neovim/neovim ~/repos/neovim && \
    curl -fLo \
        ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim && \
    (cd ~/repos/neovim && \
        make -j CMAKE_BUILD_TYPE=RelWithDebInfo && \
        sudo make install)

ADD cfgenv.sh /home/$USERNAME/tmp

RUN ~/tmp/cfgenv.sh && \
    echo "export NXS_P10K_MSG=dev-env" >> ~/.cenv

RUN nvim \
    --headless \
    -u <(sed -n '1,/call plug#end()/p' ~/.config/nvim/init.vim) \
    +PlugInstall +qa

RUN ~/nxs/env/install-lsps.sh

RUN sudo cp \
    ~/nxs/env/tmux/tmux.json \
    /usr/lib/python3.9/site-packages/powerline/config_files/themes/tmux/default.json

WORKDIR /home/$USERNAME
